# Dockerfile for Nginx serving client web files

# Base image
FROM nginx:latest

# Copy client files to Nginx web directory
COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
