version: '3.8'

services:
  websocket_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: websocket_server

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: nginx
